version: '3.8'
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    restart: always

volumes:
  grafana-storage:
  prometheus-storage: